### ISSUE TITLE
compoer install/update can't resolve dependences

### ISSUE THREAD

**Issue by bscheshirwork** [2amigos/yii2-usuario#250]
### What steps will reproduce the problem?
`compoer install`/`compoer update` on root folder of this package
### What is the expected result?
all vendor packages is installed sucessfly
### What do you get instead?
```sh
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for 2amigos/yii2-selectize-widget ^1.1 -> satisfiable by 2amigos/yii2-selectize-widget[1.1.0].
    - 2amigos/yii2-selectize-widget 1.1.0 requires bower-asset/selectize ~0.12.0 -> no matching package found.
```

**Comment by TonisOrmisson** [comment]
probably the bower-asset conf problem
if you run it as a module without haveing a project around it you need to configure the bower-assets
eg see 
https://github.com/2amigos/yii2-usuario/blob/master/.travis.yml#L33

**Comment by bscheshirwork** [comment]
So... The yii2 team now use 
```yml
    "config": {
        "process-timeout": 1800,
        "fxp-asset": {
            "enabled": false
        }
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://asset-packagist.org"
        }
    ]
```
for `yii2-app-advanced`... We can use it too? Or this is not possible? `repositories` will be use only for install "without haveing a project around", right?
